# Production environment override
services:
  php:
    build:
      context: ./
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  node:
    restart: on-failure
    command: sh -c "npm install --force && npm run build"
    tty: true
