services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-password}@database:3306/${MYSQL_DATABASE:-database}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    networks:
      - app

  # Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8}
    container_name: ${COMPOSE_PROJECT_NAME}-database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-user}
    healthcheck:
      test: ["CMD", "pg_isready -U ${MYSQL_USER:-user}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306"
    networks:
      - app
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> nodejs ###
  node:
    depends_on:
      - php
    image: node:22-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-node
    working_dir: /app
    command: sh -c "npm install --force && npm run build"
    volumes:
      - ./:/app
    networks:
      - app
  ###< nodejs ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: ${COMPOSE_PROJECT_NAME}-mailer
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app
  ###< symfony/mailer ###

  ###> phpmyadmin ###
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: on-failure
    environment:
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT:-8080}
      PMA_HOST: database
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app
  ###< phpmyadmin ###

  ###> php-worker ###
  php-worker:
    depends_on:
      - php
    build:
      context: .
      target: frankenphp_base
    container_name: ${COMPOSE_PROJECT_NAME}-php-worker
    restart: on-failure
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      DATABASE_URL: mysql://${MYSQL_USER:-user}:${MYSQL_PASSWORD:-password}@database:3306/${MYSQL_DATABASE:-database}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        publish_origins *
        demo
        anonymous
      # See https://xdebug.org/docs/all_settings#mode
    working_dir: /app
    entrypoint: ["docker-entrypoint-php-worker.sh"]
    volumes:
      - ./docker-entrypoint-php-worker.sh:/usr/local/bin/docker-entrypoint-php-worker.sh
      - ./:/app
    networks:
      - app
    tty: true
  ###< php-worker ###

volumes:
  caddy_data:
  caddy_config:
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
networks:
  app:
